#!/bin/sh
JAVA_HOME=${JAVA_HOME:=/usr}
JAVA=$JAVA_HOME/bin/java

CP1=./ccnChat.jar
CP2=lib/*
CLASSPATH=$CP1:$CP2

if [ $# = 0 ]; then
  CLASSNAME=kr.ac.snu.ccnx.apps.videochat.VideoChatClient
elif [ "$1" = "sender" ]; then
  CLASSNAME=org.ccnx.ccn.apps.ccnchat.CCNSender
else
  CLASSNAME=org.ccnx.ccn.apps.ccnchat.CCNReceiver
fi

sudo $JAVA -cp $CLASSPATH $CLASSNAME ccnx:/snu.ac.kr/chat_room
